Convert the script bit more toward bash

diff --git a/common/mysql-systemd-helper b/common/mysql-systemd-helper
--- a/common/mysql-systemd-helper
+++ b/common/mysql-systemd-helper
@@ -7,10 +7,10 @@ die() {
 # Read options from config file
 read_config() {
 	# Initial settings
-	MYSQLVER="`echo @MYSQLVER@ | sed 's|\.[0-9]\+$||'`"
+	MYSQLVER="$(echo @MYSQLVER@ | sed 's|\.[0-9]\+$||')"
 	mysql_daemon_user=mysql
 	mysql_daemon_group=mysql
-	if [ -z "$INSTANCE" ] || [ "x$INSTANCE" = "xdefault" ]; then
+	if [[ -z "$INSTANCE" || "x$INSTANCE" = "xdefault" ]]; then
 		datadir=/var/lib/mysql
 		socket="/var/run/mysql/mysql.sock"
 	else
@@ -19,29 +19,29 @@ read_config() {
 	fi
 
 	# Read options - important for multi setup
-	if [ -n "$INSTANCE" ] && [ "x$INSTANCE" \!= "xdefault" ]; then
-		opts="`/usr/bin/my_print_defaults --mysqld mysqld_multi "$2"`"
+	if [[ -n "$INSTANCE" && "x$INSTANCE" != "xdefault" ]]; then
+		opts="$(/usr/bin/my_print_defaults --mysqld mysqld_multi "$INSTANCE")"
 		tmp_opts="$opts"
 	else
-		opts="`/usr/bin/my_print_defaults --mysqld`"
+		opts="$(/usr/bin/my_print_defaults --mysqld)"
 		tmp_opts="$opts"
 	fi
 
 	# Update local variables according to the settings from config
 	for arg in $tmp_opts; do
 		case "$arg" in
-			--basedir=*)   basedir="`echo "$arg"            | sed -e 's/^[^=]*=//'`" ;;
-			--socket=*)    socket="`echo "$arg"             | sed -e 's/^[^=]*=//'`" ;;
-			--datadir=*)   datadir="`echo "$arg"            | sed -e 's/^[^=]*=//'`" ;;
-			--user=*)      mysql_daemon_user="`echo "$arg"  | sed -e 's/^[^=]*=//'`" ;;
-			--group=*)     mysql_daemon_group="`echo "$arg" | sed -e 's/^[^=]*=//'`" ;;
+			--basedir=*)   basedir="$(echo "$arg"            | sed -e 's/^[^=]*=//')" ;;
+			--socket=*)    socket="$(echo "$arg"             | sed -e 's/^[^=]*=//')" ;;
+			--datadir=*)   datadir="$(echo "$arg"            | sed -e 's/^[^=]*=//')" ;;
+			--user=*)      mysql_daemon_user="$(echo "$arg"  | sed -e 's/^[^=]*=//')" ;;
+			--group=*)     mysql_daemon_group="$(echo "$arg" | sed -e 's/^[^=]*=//')" ;;
 		esac
 	done
 }
 
 # Create new empty database if needed
 mysql_install() {
-	if ! test -d "$datadir/mysql"; then
+	if [[ ! -d "$datadir/mysql" ]]; then
 		echo "Creating MySQL privilege database... "
 		mysql_install_db --user="$mysql_daemon_user" --datadir="$datadir" || \
 		die "Creation of MySQL databse in $datadir failed"
@@ -53,7 +53,7 @@ mysql_install() {
 mysql_upgrade() {
 	# Run mysql_upgrade on every package install/upgrade. Not always
 	# necessary, but doesn't do any harm.
-	if [ -f "$datadir/.run-mysql_upgrade" ]; then
+	if [[ -f "$datadir/.run-mysql_upgrade" ]]; then
 		echo "Checking MySQL configuration for obsolete options..."
 		sed -i -e 's|^\([[:blank:]]*\)skip-locking|\1skip-external-locking|' \
 		       -e 's|^\([[:blank:]]*skip-federated\)|#\1|' /etc/my.cnf
@@ -66,11 +66,11 @@ mysql_upgrade() {
 		echo "Trying to run upgrade of MySQL databases..."
 
 		# Check whether upgrade process is not already running
-		protected="`cat /var/run/mysql/protecteddir.$INSTANCE 2> /dev/null`"
-		if [ -n "$protected" ] && [ -d "$protected" ]; then
-			pid="`cat "$protected/mysqld.pid" 2> /dev/null`"
-			if [ "$pid" ] && [ -d "/proc/$pid" ] &&
-			   [ "`readlink "/proc/$pid/exe" | grep "mysql"`" ]; then
+		protected="$(cat "/var/run/mysql/protecteddir.$INSTANCE" 2> /dev/null)"
+		if [[ -n "$protected" && -d "$protected" ]]; then
+			pid="$(cat "$protected/mysqld.pid" 2> /dev/null)"
+			if [[ "$pid" && -d "/proc/$pid" ]] &&
+			   [[ $(readlink "/proc/$pid/exe" | grep -q "mysql") ]]; then
 				die "Another upgrade in already in progress!"
 			else
 				echo "Stale files from previous upgrade detected, cleaned them up"
@@ -78,13 +78,13 @@ mysql_upgrade() {
 				rm -f "/var/run/mysql/protecteddir.$INSTANCE"
 			fi
 		fi
-		protected="`mktemp -d -p /var/tmp mysql-protected.XXXXXX | tee /var/run/mysql/protecteddir.$INSTANCE`"
+		protected="$(mktemp -d -p /var/tmp mysql-protected.XXXXXX | tee "/var/run/mysql/protecteddir.$INSTANCE")"
 		[ -n "$protected" ] || die "Can't create a tmp dir '$protected'"
 
 		# Create a secure tmp dir
 		chown --no-dereference "$mysql_daemon_user:$mysql_daemon_group" "$protected"
 		chmod 0700  "$protected"
-		[ "`ls -ld "$protected" | grep "^drwx------[\\.\+]\?[[:blank:]]\+[0-9]\+[[:blank:]]\+$mysql_daemon_user[[:blank:]]\+$mysql_daemon_group[[:blank:]]\+.*"`" ] || \
+		[[ $(ls -ld "$protected" | grep -q "^drwx------[\\.\+]\?[[:blank:]]\+[0-9]\+[[:blank:]]\+$mysql_daemon_user[[:blank:]]\+$mysql_daemon_group[[:blank:]]\+.*") ]] || \
 			die "Can't secure tmp dir '$protected'"
 
 		# Run protected MySQL accessible only though socket in our directory
@@ -108,7 +108,7 @@ mysql_upgrade() {
 			echo "Everything upgraded successfully"
 			up_ok=""
 			rm -f "$datadir/.run-mysql_upgrade"
-			[ "`grep "^$MYSQLVER" "$datadir/mysql_upgrade_info" 2> /dev/null`" ] || \
+			[[ $(grep -q "^$MYSQLVER" "$datadir/mysql_upgrade_info" 2> /dev/null) ]] || \
 				echo -n "@MYSQLVER@" > "$datadir/mysql_upgrade_info"
 		else
 			echo "Upgrade failed"
@@ -117,23 +117,23 @@ mysql_upgrade() {
 
 		# Shut down MySQL
 		echo "Shuting down protected MySQL"
-		kill "`cat "$protected/mysqld.pid"`"
-		for i in `seq 1 30`; do
+		kill "$(cat "$protected/mysqld.pid")"
+		for i in {1..30}; do
 			/usr/bin/mysqladmin --socket="$protected/mysql.sock" ping > /dev/null 2>&1 || break
 		done
-		/usr/bin/mysqladmin --socket="$protected/mysql.sock" ping > /dev/null 2>&1 && kill -9 "`cat "$protected/mysqld.pid"`"
+		/usr/bin/mysqladmin --socket="$protected/mysql.sock" ping > /dev/null 2>&1 && kill -9 "$(cat "$protected/mysqld.pid")"
 
 		# Cleanup
 		echo "Final cleanup"
 		rm -rf "$protected" "/var/run/mysql/protecteddir.$INSTANCE"
-		[ -z "$up_ok" ] || die "Something failed during upgrade, please check logs"
+		[[ -z "$up_ok" ]] || die "Something failed during upgrade, please check logs"
 	fi
 }
 
 mysql_wait() {
-	[ -z "$1" ] || socket="$1"
+	[[ -z "$1" ]] || socket="$1"
 	echo "Waiting for MySQL to start"
-	for i in `seq 1 60`; do
+	for i in {1..60}; do
 		/usr/bin/mysqladmin --socket="$socket" ping > /dev/null 2>&1 && break
 		sleep 1
 	done
